config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admins
  mount_devise_token_auth_for 'User', at: 'users', controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  namespace :admin_panel do
    resources :tags
    resources :categories
    resources :recipes
    resources :ingredients
  end

  resources :recipes, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  get 'current_user', to: 'current_user#show'
  get 'favorites', to: 'recipes#favorites'
  root to: 'home#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category, optional: true
  has_many :likes

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  has_many :ingredient_recipes, dependent: :destroy
  has_many :ingredients, through: :ingredient_recipes
  accepts_nested_attributes_for :ingredient_recipes, allow_destroy: true,
    reject_if: ->(record) { record[:ingredient_id].blank? }

  has_many :recipe_tags, dependent: :destroy
  has_many :tags, through: :recipe_tags
  accepts_nested_attributes_for :recipe_tags, allow_destroy: true,
    reject_if: ->(record) { record[:tag_id].blank? }

  validates_presence_of :name, :description, :category_id
end

app/controllers/admin_panel/categories_controller.rb
class AdminPanel::CategoriesController < AdminPanel::HomeController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_panel_category_path(@category), notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_panel_category_path(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_panel_categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :icon)
    end
end

app/controllers/admin_panel/home_controller.rb
class AdminPanel::HomeController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/admin_panel/ingredients_controller.rb
class AdminPanel::IngredientsController < AdminPanel::HomeController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to admin_panel_ingredient_path(@ingredient), notice: 'Ingredient was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to admin_panel_ingredient_path(@ingredient), notice: 'Ingredient was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to admin_panel_ingredients_url, notice: 'Ingredient was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :measurement)
    end
end

app/controllers/admin_panel/recipes_controller.rb
class AdminPanel::RecipesController < AdminPanel::HomeController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 10

    @recipes = Recipe
      .select(:id, :name, :description, :category_id)
      .includes(:category)
      .paginate(page: page, per_page: per_page)
      .order(created_at: :desc)
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @categories = Category.all
    @tags = Tag.all
    @ingredients = Ingredient.all

    3.times { @recipe.images.build }
    5.times { @recipe.ingredient_recipes.build }
    3.times { @recipe.recipe_tags.build }
  end

  # GET /recipes/1/edit
  def edit
    @categories = Category.all
    @tags = Tag.all
    @ingredients = Ingredient.all
    @recipe.images.build
    @recipe.ingredient_recipes.build
    @recipe.recipe_tags.build
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to edit_admin_panel_recipe_path(@recipe), notice: 'Recipe was successfully created.' }
      else
        @categories = Category.all
        @tags = Tag.all
        @ingredients = Ingredient.all
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /recipes/1
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to edit_admin_panel_recipe_path(@recipe), notice: 'Recipe was successfully updated.' }
      else
        @categories = Category.all
        @tags = Tag.all
        @ingredients = Ingredient.all
        format.html { render :edit }
      end
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to admin_panel_recipes_url, notice: 'Recipe was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe
        .includes(:category, :images, :recipe_tags, :tags, :ingredient_recipes,
                  :ingredients)
        .find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(
        :name,
        :description,
        :category_id,
        images_attributes: [:id, :path, :selected, :_destroy],
        ingredient_recipes_attributes: [:id, :amount, :ingredient_id,
                                        :_destroy],
        recipe_tags_attributes: [:id, :amount, :tag_id, :_destroy]
      )
    end
end

app/controllers/admin_panel/tags_controller.rb
class AdminPanel::TagsController < AdminPanel::HomeController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_panel_tag_path(@tag), notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tags/1
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_panel_tag_path(@tag), notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to admin_panel_tags_url, notice: 'Tag was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < HomeController
  # GET /recipes.json
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 10

    @liked = []
    if user_signed_in?
      @liked = current_user
        .likes.map { |like| { like_id: like.id,  recipe_id: like.recipe_id } }
        .group_by{ |like| like[:recipe_id] }
    end

    @recipes = Recipe
      .select(:id, :name, :description, :category_id, :created_at)
      .paginate(page: page, per_page: per_page)
      .includes(:category, :images, :recipe_tags, :tags)
      .order(created_at: :desc)
  end

  # GET /recipes/1.json
  def show
    @recipe = Recipe
      .includes(:category, :images, :recipe_tags, :tags, :ingredients)
      .find params[:id]
  end

  # GET /favorites.json
  def favorites
    page = params[:page] || 1
    per_page = params[:per_page] || 10

    @recipes = Recipe
      .select(:id, :name, :description, :category_id, :created_at, 'likes.id AS like_id')
      .joins(:likes)
      .where('likes.user_id = ?', current_user.id)
      .paginate(page: page, per_page: per_page)
      .includes(:category, :images, :recipe_tags, :tags)
      .order(created_at: :desc)
    @liked = @recipes
      .map { |recipe| { like_id: recipe.like_id, recipe_id: recipe.id } }
      .group_by{ |like| like[:recipe_id] }
    render 'recipes/index'
  end
end

app/views/admin_panel/recipes/_form.html.erb
<%= form_for [:admin_panel, @recipe] do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'editable' %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, @categories, :id, :name, {}, class: 'form-control' %>
  </div>

  <br>
  <h5>Images</h5>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Preview</th>
      <th>Selected</th>
      <th>Delete</th>
    </tr>
    <%= f.fields_for :images, @recipe.images do |f_image| %>
      <% image = f_image.object %>
      <tr>
        <td>
          <%= f_image.file_field :path %>
        </td>
        <% if image.persisted? %>
          <td>
            <%= image_tag(image.path.thumb.url, height: '50') %>
          </td>
          <td>
            <%= f_image.check_box :selected, class: 'form-control' %>
          </td>
          <td>
            <%= f_image.check_box "_destroy", class: 'form-control' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <br>
  <h5>Ingredients</h5>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Delete</th>
    </tr>
    <%= f.fields_for :ingredient_recipes, @recipe.ingredient_recipes do |f_ingredient_recipe| %>
      <% ingredient_recipe = f_ingredient_recipe.object %>
      <tr>
        <td>
          <%= f_ingredient_recipe.collection_select :ingredient_id, @ingredients, :id, :name, {include_blank: true}, class: 'form-control' %>
        </td>
        <td>
          <%= f_ingredient_recipe.text_field :amount, class: 'form-control' %>
        </td>
        <% if ingredient_recipe.persisted? %>
          <td>
            <%= f_ingredient_recipe.check_box "_destroy", class: 'form-control' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <br>
  <h5>Tags</h5>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Delete</th>
    </tr>
    <%= f.fields_for :recipe_tags, @recipe.recipe_tags do |f_recipe_tag| %>
      <% recipe_tag = f_recipe_tag.object %>
      <tr>
        <td>
          <%= f_recipe_tag.collection_select :tag_id, @tags, :id, :name, {include_blank: true}, class: 'form-control' %>
        </td>
        <td>
          <%= f_recipe_tag.text_field :amount, class: 'form-control' %>
        </td>
        <% if recipe_tag.persisted? %>
          <td>
            <%= f_recipe_tag.check_box "_destroy", class: 'form-control' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin_panel/recipes/edit.html.erb
<div class="row">
  <div class="col-6">
    <h3>Editing Recipe</h3>

    <%= render 'form' %>

    <%= link_to 'Back', admin_panel_recipes_path %>
  </div>
</div>

app/views/admin_panel/recipes/index.html.erb
<h3>Listing Recipes</h3>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.id %></td>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.category.name %></td>
        <td><%= link_to 'Edit', edit_admin_panel_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', admin_panel_recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @posts %>

<br>

<%= link_to 'New Recipe', new_admin_panel_recipe_path, class: 'btn btn-primary', role: 'button' %>

app/views/admin_panel/recipes/new.html.erb
<div class="row">
  <div class="col-6">
    <h3>New Recipe</h3>

    <%= render 'form' %>

    <%= link_to 'Back', admin_panel_recipes_path %>
  </div>
</div>